# Generated by Django 6.0.2 on 2026-02-15 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='golfcourse',
            name='logic_type',
            field=models.CharField(choices=[('foreup', 'ForeUp Software'), ('foreup_new', 'ForeUp New Layout'), ('cps', 'CPS Golf (Capital Hills)'), ('cps_old_post', 'CPS Golf (Old Post)'), ('frear', 'Frear Park Custom'), ('schenectady', 'Schenectady Muni')], max_length=20),
        ),
    ]
