# Generated by Django 6.0.2 on 2026-04-26 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_bookingrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='golfcourse',
            name='advance_booking_days',
            field=models.IntegerField(default=7, help_text='Number of days in advance this course allows booking'),
        ),
    ]
