# Generated by Django 5.2.11 on 2026-04-26 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_alter_bookingrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
